# Generated by Django 3.0.5 on 2020-04-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200412_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='name',
        ),
        migrations.RemoveField(
            model_name='study',
            name='no_of_years',
        ),
        migrations.AddField(
            model_name='study',
            name='number_of_years',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='study',
            name='study_name',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='study',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='study',
            name='language',
            field=models.TextField(default='Unknown'),
        ),
    ]
