# Generated by Django 3.0.5 on 2020-04-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200412_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'managed': False},
        ),
    ]
