# Generated by Django 3.0.5 on 2020-04-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200412_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('credits', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id_exam', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.CharField(blank=True, max_length=45, null=True)),
                ('resit', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Exam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id_result', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('passed', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=1)),
                ('street_name', models.CharField(max_length=45)),
                ('street_number', models.CharField(max_length=45)),
                ('postal_code', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('start_year', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=45, null=True)),
                ('street_name', models.CharField(blank=True, max_length=45, null=True)),
                ('street_number', models.CharField(blank=True, max_length=45, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('salary', models.CharField(blank=True, max_length=45, null=True)),
                ('study_counselor', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Teacher',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='study',
            table='Study',
        ),
    ]
