# Generated by Django 3.0.5 on 2020-04-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200412_0251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': True},
        ),
    ]
