# Generated by Django 3.0.5 on 2020-04-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200416_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='picture_url',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
