# Generated by Django 3.0.5 on 2020-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_teacher_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_pic',
            field=models.ImageField(default='', upload_to='../templates/pictures'),
        ),
    ]
