# Generated by Django 3.0.5 on 2020-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200416_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_pic',
            field=models.ImageField(default='', upload_to='thecreativegenius/templates/pictures'),
        ),
    ]
