# Generated by Django 3.0.5 on 2020-04-19 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_auto_20200416_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, max_length=45, null=True)),
                ('student_user_id', models.ForeignKey(blank=True, db_column='student_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Student')),
                ('teacher_user_id', models.ForeignKey(blank=True, db_column='teacher_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
